In [1]:
import numpy as np
import pandas as pd

import bokeh_catplot

import bokeh.io
import bokeh.plotting

bokeh.io.output_notebook()

Loading BokehJS ...

In [2]:
#What does the data look like?
#Read data in

df = pd.read_csv('C:/Users/yang1/git/bootcamp/data/nbha_ctx_T.csv',na_values='*')



In [3]:
#Question: How do CTX levels change over 2 years
p = bokeh_catplot.strip(
    data=df,
    cats='ID',
    val='ctx (pg/ml)',
    tooltips=[
        ('ctx level', '@{ctx (pg/ml)} pg/ml')
     ],
        
)
%config InlineBackend.figure_format = 'png'

bokeh.io.show(p)


In [4]:
p = bokeh_catplot.strip(
    data=df,
    cats='ID',
    val='ctx (pg/ml)',
    horizontal=False,
    jitter=True,
    frame_height=250,
    tooltips=[
        ('ctx level', '@{ctx (pg/ml)} pg/ml')
     ],
)

p = bokeh_catplot.box(
    data=df,
    cats='ID',
    val='ctx (pg/ml)',
    horizontal=False,
    whisker_caps=True,
    display_points=False,
    box_kwargs=dict(fill_color=None, line_color='gray'),
    median_kwargs=dict(line_color='gray'),
    whisker_kwargs=dict(line_color='gray'),
    p=p,
)


bokeh.io.show(p)


In [20]:
p = bokeh_catplot.ecdf(
    data=df,
    cats='ID',
    val='ctx (pg/ml)',
    style='staircase',
    show_legend=True,
    palette=bokeh.palettes.Blues256[:-100:17]
)

bokeh.io.show(p)

In [6]:
p.output_backend = 'svg'
bokeh.io.export_svgs(p, filename='nbha_ctx_24jun2020.svg')
p.output_backend = 'canvas'

In [7]:
rg = np.random.default_rng()

In [8]:
#create two numpy array for 2 categories mo0 and mo3 with the ctx values
ctx_mo0 = df.loc[df['ID']=='mo0', 'ctx (pg/ml)'].values
ctx_mo3 = df.loc[df['ID']=='mo3', 'ctx (pg/ml)'].values
ctx_mo6 = df.loc[df['ID']=='mo6', 'ctx (pg/ml)'].values
ctx_mo9 = df.loc[df['ID']=='mo9', 'ctx (pg/ml)'].values
ctx_mo12 = df.loc[df['ID']=='mo12', 'ctx (pg/ml)'].values
ctx_mo15 = df.loc[df['ID']=='mo15', 'ctx (pg/ml)'].values
ctx_mo18 = df.loc[df['ID']=='mo18', 'ctx (pg/ml)'].values
ctx_mo21 = df.loc[df['ID']=='mo21', 'ctx (pg/ml)'].values
ctx_mo24 = df.loc[df['ID']=='mo24', 'ctx (pg/ml)'].values

# bootstrap CI for %change between baseline and mo3

In [9]:
def draw_bs_rep(data, func, rg):
    """Compute a bootstrap replicate from data."""
    bs_sample = rg.choice(data, size=len(data))
    return func(bs_sample)


# Perform the drug holiday experiment 100,000 times with a random number generator that picks out#
#n=66 @ mo0 and n=64 @mo3.##
n_reps = 100000
bs_reps_mo0 = np.array(
    [draw_bs_rep(ctx_mo0, np.mean, rg) for _ in range(n_reps)]
)
bs_reps_mo3 = np.array(
    [draw_bs_rep(ctx_mo3, np.mean, rg) for _ in range(n_reps)]
)

# 100,000 difference of means were also generated 
bd_reps_diff = (bs_reps_mo3 - bs_reps_mo0)/(bs_reps_mo0)

# Report the confidence interval with 95% confidence for the difference of means 

print ('CI for %change between month 0 and month 3')
np.percentile(bd_reps_diff, [2.5, 97.5])

CI for %change between month 0 and month 3


array([0.03873743, 0.41106429])

# bootstrap CI for %change between baseline and month 6

In [10]:
def draw_bs_rep(data, func, rg):
    """Compute a bootstrap replicate from data."""
    bs_sample = rg.choice(data, size=len(data))
    return func(bs_sample)


# Perform the drug holiday experiment 100,000 times with a random number generator that picks out#
#n=66 @ mo0 and n=64 @mo3.##
n_reps = 100000
bs_reps_mo0 = np.array(
    [draw_bs_rep(ctx_mo0, np.mean, rg) for _ in range(n_reps)]
)
bs_reps_mo6 = np.array(
    [draw_bs_rep(ctx_mo6, np.mean, rg) for _ in range(n_reps)]
)

# 100,000 difference of means were also generated 
bd_reps_diff = (bs_reps_mo6 - bs_reps_mo0)/(bs_reps_mo0)

# Report the confidence interval with 95% confidence for the difference of means 
print ('CI for %change between month 0 and month 6')
np.percentile(bd_reps_diff, [2.5, 97.5])

CI for %change between month 0 and month 6


array([0.15274771, 0.59117057])

## Bootstrap for CI of %change between baseline and mo24

In [11]:
def draw_bs_rep(data, func, rg):
    """Compute a bootstrap replicate from data."""
    bs_sample = rg.choice(data, size=len(data))
    return func(bs_sample)


# Perform the drug holiday experiment 100,000 times with a random number generator that picks out#
#n=66 @ mo0 and n=64 @mo3.##
n_reps = 100000
bs_reps_mo0 = np.array(
    [draw_bs_rep(ctx_mo0, np.mean, rg) for _ in range(n_reps)]
)
bs_reps_mo24 = np.array(
    [draw_bs_rep(ctx_mo24, np.mean, rg) for _ in range(n_reps)]
)

# 100,000 difference of means were also generated 
bd_reps_diff = (bs_reps_mo24 - bs_reps_mo0)/(bs_reps_mo0)

# Report the confidence interval with 95% confidence for the difference of means 
print ('CI for %change between month 0 and month 24')
np.percentile(bd_reps_diff, [2.5, 97.5])

CI for %change between month 0 and month 24


array([0.19388124, 1.15110095])

In [12]:
years = ['mo0', 'mo3']
p = bokeh.plotting.figure(
    frame_height=100,
    frame_width=250,
    x_axis_label='ctx (pg/ml)',
    y_range=years,
)

p.circle([ctx_mo0.mean(), ctx_mo3.mean()], years, size=5)
p.line(conf_int_1975, ['mo0']*2, line_width=3)
p.line(conf_int_2012, ['mo3']*2, line_width=3)
bokeh.io.show(p)

NameError: name 'conf_int_1975' is not defined